name: example
description: Example project for form_builder_file_picker package
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^7.0.0
  form_builder_file_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true