name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 1.2.1-nullsafety.1
homepage: https://github.com/danvick/form_builder_file_picker

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^7.0.0
  file_picker: ^4.2.4
  permission_handler: ^8.3.0
  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
flutter:
